development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: redis://default:ziVvSuYRPpGksaQhtHjj8mVU3R5v3gqc@redis-15728.c91.us-east-1-3.ec2.cloud.redislabs.com:15728
  #channel_prefix: textanyone_production
